.TH "ponto_t" 3 "Tue May 21 2019" "Trabalho Prático I - Estruturas de Dados" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ponto_t \- ponto com coordenadas x, y  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ponto com coordenadas x, y 
.PP
Definition at line 42 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Prático I - Estruturas de Dados from the source code\&.
