.TH "structures" 3 "Tue May 21 2019" "Trabalho Prático I - Estruturas de Dados" \" -*- nroff -*-
.ad l
.nh
.SH NAME
structures \- Copyright [2019] <Paulo almeida>=''>  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLinkedQueue\fP"
.br
.RI "Fila Encadeada\&. "
.ti -1c
.RI "class \fBLinkedStack\fP"
.br
.RI "Pilha encadeada\&. "
.in -1c
.SH "Detailed Description"
.PP 
Copyright [2019] <Paulo almeida>=''> 
.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Prático I - Estruturas de Dados from the source code\&.
