.TH "structures::LinkedStack< T >" 3 "Tue May 21 2019" "Trabalho Prático I - Estruturas de Dados" \" -*- nroff -*-
.ad l
.nh
.SH NAME
structures::LinkedStack< T > \- Pilha encadeada\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linked_stack\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkedStack\fP ()"
.br
.RI "construtor "
.ti -1c
.RI "\fB~LinkedStack\fP ()"
.br
.RI "destrutor "
.ti -1c
.RI "void \fBclear\fP ()"
.br
.RI "limpa pilha, desaloca memória "
.ti -1c
.RI "void \fBpush\fP (const T &data)"
.br
.RI "empilha "
.ti -1c
.RI "T \fBpop\fP ()"
.br
.RI "desempilha "
.ti -1c
.RI "T & \fBtop\fP () const"
.br
.RI "retorna dado no topo "
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.RI "retorna pilha vazia "
.ti -1c
.RI "std::size_t \fBsize\fP () const"
.br
.RI "retorna tamanho da pilha "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class structures::LinkedStack< T >"
Pilha encadeada\&. 
.PP
Definition at line 12 of file linked_stack\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Prático I - Estruturas de Dados from the source code\&.
