.TH "structures::LinkedQueue< T >" 3 "Tue May 21 2019" "Trabalho Prático I - Estruturas de Dados" \" -*- nroff -*-
.ad l
.nh
.SH NAME
structures::LinkedQueue< T > \- Fila Encadeada\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linked_queue\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkedQueue\fP ()"
.br
.RI "método construtor "
.ti -1c
.RI "\fB~LinkedQueue\fP ()"
.br
.RI "método destrutor "
.ti -1c
.RI "void \fBclear\fP ()"
.br
.RI "limpa fila, desaloca memória "
.ti -1c
.RI "void \fBenqueue\fP (const T &data)"
.br
.RI "método enfileirar "
.ti -1c
.RI "T \fBdequeue\fP ()"
.br
.RI "método desenfileirar "
.ti -1c
.RI "T & \fBfront\fP () const"
.br
.RI "método retorna primeiro dado "
.ti -1c
.RI "T & \fBback\fP () const"
.br
.RI "método retorna último dado "
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.RI "método retorna se a fila está vazia "
.ti -1c
.RI "std::size_t \fBsize\fP () const"
.br
.RI "método retorna tamanho da fila "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class structures::LinkedQueue< T >"
Fila Encadeada\&. 
.PP
Definition at line 13 of file linked_queue\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Prático I - Estruturas de Dados from the source code\&.
